### ISSUE TITLE
get two codes to give same answers!

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/ChemicalTangents#11]
somehow @adrn and @davidwhogg get different likelihood values.

**Comment by davidwhogg** [comment]
first step: Compare our energy calculations for matched stars.

**Comment by davidwhogg** [comment]
second step: Check that the internals of the LF are identical for some set of stars.

**Comment by davidwhogg** [comment]
third step: audit our LF math

**Comment by adrn** [comment]
Steps 1 and 2 are done (try it: `cd pkg; py.test chemtrails`)

Making a new issue for step 3, because that's critical!

**Comment by davidwhogg** [comment]
YAY
