### ISSUE TITLE
APOGEE RC vs. GALAH

### ISSUE THREAD

**Issue by adrn** [davidwhogg/ChemicalTangents#13]
I ran on YST's red clump stars from APOGEE and on all RGB stars with SNR > 20 in GALAH. See a few sample plots below; bug?!

# [O/H]
### APOGEE RC
![corner-o_h](https://user-images.githubusercontent.com/583379/44891604-879f3100-ac9d-11e8-8813-87ef2e62d510.png)
### GALAH
![corner-o_h](https://user-images.githubusercontent.com/583379/44891606-8a018b00-ac9d-11e8-8292-41dc600e0bf7.png)

# [Fe/H]
### APOGEE RC
![corner-fe_h](https://user-images.githubusercontent.com/583379/44891616-9a196a80-ac9d-11e8-99f2-5d7a7b936fc4.png)
### GALAH
![corner-fe_h](https://user-images.githubusercontent.com/583379/44891620-9c7bc480-ac9d-11e8-9cd8-1b4db4e9938a.png)

**Comment by davidwhogg** [comment]
Okay big question: Can we SEE in the APOGEE data (like we can see in GALAH) that the abundance ratio distribution is not symmetric around the midplane?
